### ISSUE TITLE
Responsives of the website.

### ISSUE THREAD

**Issue by Namanb454** [niteshjitender/HacktoberFest2022#1]
> The site is not responsive for the mobile application.
> Margin/Padding is not considered properly.
> Logo Image(HACOTBERFEST) is not visible in mobile application.
> Contributors section shifting towards right.

**Proposal**
> I will make the site responsive for both application.
> Margin/Padding will be done properly.
> Logo image will be visible.
> Contributors section will be shift to center.

**Comment by Namanb454** [comment]
@niteshjitender Please assign this issue to me.

**Comment by niteshjitender** [comment]
Hi Naman,
You can continue to fix this issue. I have assigned this to you.

**Comment by AbhishekTiwari23** [comment]
@niteshjitender hello, I am a beginner who wants to work on an issue. Can you please assign me or give me some tasks so that I can contribute?

**Comment by niteshjitender** [comment]
@AbhishekTiwari23 
Hi Abhishek, 
Please complete the beginners' tasks first. I will raise some issues today you can choose one of them after finishing the beginners' tasks.

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23 Hi Abhishek, Please complete the beginners' tasks first. I will raise some issues today you can choose one of them after finishing the beginners' tasks.

Ok, I will give my best.

**Comment by niteshjitender** [comment]
> > @AbhishekTiwari23 Hi Abhishek, Please complete the beginners' tasks first. I will raise some issues today you can choose one of them after finishing the beginners' tasks.
> 
> Ok, I will give my best.

For your reference: [README](https://github.com/niteshjitender/HacktoberFest2022/blob/main/README.md)
Just follow the steps to get started.

**Comment by swastik-bose007** [comment]
i have fixed the responsiveness issues with a slight modification in layout please accept my contribution
