### ISSUE TITLE
Add contributors section in Readme (No Coding, Documentation)

### ISSUE THREAD

**Issue by niteshjitender** [niteshjitender/HacktoberFest2022#10]
Add a contributors section in Readme in which a Profile pic of the contributors is shown.

**Comment by aritroo** [comment]
I want to work on it please assign it to me

**Comment by sourabhchouhan07** [comment]
hii nitesh , I want to work on this issue please **assign** it to me

**Comment by HimangsKalita** [comment]
I am contributing

**Comment by HimangsKalita** [comment]
could you please accept the pull request #13

**Comment by niteshjitender** [comment]
Hi @aritroo 

Assigning this issue to you. Please raise PR after completing this.
Don't forget to give a star. 😉

Thanks & Regards
Jitender Singh Chhapola
