### ISSUE TITLE
Animate the title on hovering

### ISSUE THREAD

**Issue by niteshjitender** [niteshjitender/HacktoberFest2022#8]
Enhancement: Animate the word 'First' on hovering in the website title. 
Create any cool animation when we hover on the word 'First'.

eg-Create an animation in which each alphabet of the word jumps or dances when we hover on that. This is just an example, you can use your own imagination or can implement the same.

**Comment by Suhaas10** [comment]
I want take this

**Comment by niteshjitender** [comment]
Hi @Suhaas10 

Assigning this issue to you. You can start work on this. Please raise PR after completing this.
Don't forget to give a star. 😉

Thanks & Regards
Jitender Singh Chhapola

**Comment by Suhaas10** [comment]
How do I run this vanilla JS project locally? @niteshjitender

**Comment by Suhaas10** [comment]
Done [https://github.com/niteshjitender/HacktoberFest2022/pull/14](url)

**Comment by niteshjitender** [comment]
'First' keyword is highlighted not animated. Not closing this issue. Although your PR is accepted. 

> Done [https://github.com/niteshjitender/HacktoberFest2022/pull/14](url)

**Comment by niteshjitender** [comment]
This issue is still open and anybody who is up to this. Please comment.

**Comment by LOKESHPRASAD12** [comment]
hey can you assign it to me I'll try to do my best

**Comment by RAHUL14KUMAR** [comment]
hi i am hacktoberfest participant  can u please assign this issue to me.

**Comment by Suhaas10** [comment]
@niteshjitender Please assign back to me, I have created new PR

**Comment by piyushkandari** [comment]
hi i am new to open source please assign this to me for learning

**Comment by adi-uchiha** [comment]
Working on this, will soon submit a PR
