### ISSUE TITLE
Creation of the logo (No coding skills, designing)

### ISSUE THREAD

**Issue by niteshjitender** [niteshjitender/HacktoberFest2022#9]
New Feature: Create a logo with the theme colors of 'My First Contribution.

**Comment by Yuji-Itadorii** [comment]
hey @niteshjitender  , I am a participant of Hacktoberfest 2022, please assign this issue to me under the program.

**Comment by niteshjitender** [comment]
Hi @Yuji-Itadorii 

Assigning this issue to you. Please raise PR after completing this. I will also recommend you to complete the tasks in [Readme](https://github.com/niteshjitender/HacktoberFest2022/blob/main/README.md) file. 
Don't forget to give a star. 😉

Thanks & Regards
Jitender Singh Chhapola

**Comment by Yuji-Itadorii** [comment]
Hi @niteshjitender , please review my pull request and let me know if you found any isssue :)
